#-----------------------
# provider variables
#-----------------------
variable "project_id" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "Region to deploy GCP resources"
  type        = string
}

#variable "zone" {
#  description = "Zone to deploy GCP resources"
#  type        = string
#}


###-------------------------
# Consul & Nomad
#---------------------------
variable "environment" {
  description = "Environment setting for Consul and Nomad config"
  type        = string
}


###-------------------------
# Consul
#---------------------------
variable "consul_server_machine_type" {
  description = "Consul server machine type/size"
  type        = string
  default     = "e2-medium"
}

variable "consul_server_tag" {
  description = "Server tag used for by Auto-join and also GCP firewall rules"
  type        = string
  default     = "consulserver"
}

variable "consul_gossip_key" {
  description = "Consul gossip key, generated by 'consul keygen'"
  type        = string
}

variable "consul_server_count" {
  description = "Number of Consul servers, should be 1, 3, or 5"
  type        = number
  default     = 3
}


###-------------------------
# Nomad
#---------------------------
variable "nomad_server_machine_type" {
  description = "Nomad server machine type/size"
  type        = string
  default     = "e2-medium"
}

variable "nomad_server_tag" {
  description = "Server tag used by GCP firewall rules"
  type        = string
  default     = "nomadserver"
}

variable "nomad_client_machine_type" {
  description = "Nomad client machine type/size. Clients run your workloads."
  type        = string
  default     = "n2d-standard-2"
}

variable "nomad_client_tag" {
  description = "Server tag used by GCP firewall rules"
  type        = string
  default     = "nomadclient"
}

variable "nomad_gossip_key" {
  description = "Nomad gossip key, generated by 'openssl rand -base64 32'"
  type        = string
}

variable "nomad_server_count" {
  description = "Number of Nomad servers, should be 1, 3, or 5"
  type        = number
  default     = 3
}

variable "nomad_client_count" {
  description = "Number of Nomad servers, should be 1, 3, or 5"
  type        = number
  default     = 2
}
