---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "block-internet-egress"
  annotations:
    description: "Blocks egress traffic to the internet, with exceptions"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "SAddr"
        values:
        - 172.17.0.0/16		# Docker bridge network CIDR (default)
        - 10.162.0.0/20		# VPC subnet CIDR
      - index: 0
        operator: "NotDAddr"
        values:
        - 169.254.169.254	# GCE metadata endpoint
        - 127.0.0.1
        - 10.162.0.0/20		# VPC subnet CIDR
        - 172.17.0.0/16		# Docker bridge network CIDR (default)
      matchBinaries:
      - operator: "NotIn"
        values:
         - "/usr/bin/nslookup"
      matchActions:
      - action: Sigkill
