---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "log-file-access"
  annotations:
    description: "Log access to files"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    args:
    - index: 0
      type: "file"
    - index: 1
      type: "int"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/alloc"
        - "/local"
        - "/secrets"
      matchActions:
      - action: Post
        rateLimit: 1m
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/etc/passwd"
      matchBinaries:
      - operator: "NotIn"
        values:
         - "/usr/bin/java"
         - "/usr/bin/runc"
         - "/usr/bin/tetragon"
      matchActions:
      - action: Post
        rateLimit: 1m
